-- SQL de bootstrap minimo para iniciar o projeto.
-- Dialeto alvo: PostgreSQL/Supabase.
-- Depois deste bootstrap, o backend complementa o restante do schema no startup.

CREATE TABLE usuarios (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(160) NOT NULL,
	email VARCHAR(180) NOT NULL UNIQUE,
	senha_hash VARCHAR(255) NOT NULL,
	tipo_usuario VARCHAR(30) NOT NULL,
	ativo SMALLINT NOT NULL DEFAULT 1,
	data_cadastro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE turmas (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(120) NOT NULL,
	descricao TEXT,
	ativa SMALLINT NOT NULL DEFAULT 1,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alunos_turmas (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	aluno_id INTEGER NOT NULL REFERENCES usuarios(id),
	turma_id INTEGER NOT NULL REFERENCES turmas(id),
	status VARCHAR(20) NOT NULL DEFAULT 'ativo',
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(aluno_id, turma_id)
);

CREATE TABLE inscricoes (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(160) NOT NULL,
	email VARCHAR(180) NOT NULL UNIQUE,
	telefone VARCHAR(40),
	respostas JSON,
	tipo_logradouro VARCHAR(60),
	logradouro VARCHAR(180),
	numero VARCHAR(30),
	complemento VARCHAR(120),
	municipio VARCHAR(120),
	estado VARCHAR(80),
	pais VARCHAR(80),
	cep VARCHAR(20),
	comprovante_url TEXT,
	termo_assinado_url TEXT,
	status VARCHAR(20) NOT NULL DEFAULT 'pendente',
	ra_codigo VARCHAR(40),
	data_inscricao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	data_reprovacao TIMESTAMP
);

CREATE TABLE produtos (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(180) NOT NULL,
	preco DECIMAL(12,2) NOT NULL DEFAULT 0,
	descricao TEXT,
	tipo VARCHAR(40) NOT NULL,
	estoque INTEGER NOT NULL DEFAULT 0,
	vendedor_id INTEGER REFERENCES usuarios(id),
	url_contato_direto TEXT,
	ativo SMALLINT NOT NULL DEFAULT 1,
	deleted_at TIMESTAMP,
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pedidos (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	usuario_id INTEGER REFERENCES usuarios(id),
	total DECIMAL(12,2) NOT NULL DEFAULT 0,
	status VARCHAR(30) NOT NULL DEFAULT 'pendente',
	payment_id VARCHAR(120),
	mercado_external_reference VARCHAR(120),
	data_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE notifications (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	usuario_id INTEGER REFERENCES usuarios(id),
	tipo VARCHAR(80),
	mensagem TEXT NOT NULL,
	canal VARCHAR(40) DEFAULT 'sistema',
	enviado SMALLINT NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE armazenamento_universal (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	chave VARCHAR(180) NOT NULL UNIQUE,
	tipo_recurso VARCHAR(80) NOT NULL,
	subtipo VARCHAR(80),
	encrypted SMALLINT NOT NULL DEFAULT 1,
	algorithm VARCHAR(40) NOT NULL DEFAULT 'aes-256-gcm',
	iv TEXT,
	auth_tag TEXT,
	payload_base64 TEXT NOT NULL,
	metadata_json JSON,
	supabase_bucket VARCHAR(120),
	supabase_path TEXT,
	criado_por_id INTEGER REFERENCES usuarios(id),
	criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
